### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [juliangb44/conditional-post-card#1]
Hola Julián,

al probar el ejercicio veo esto:
![image](https://user-images.githubusercontent.com/92524023/203629613-0f6ec80d-fe00-49d9-bef6-207127dbf0ef.png)

Además, los selectores de role, city y country no funcionan. Échale un vistazo cuando puedas👌

**Comment by juliangb44** [comment]
Corregido!! :))
